# コンテナを作成し、Cloud RunにデプロイするCloud Build定義。
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=private_repo_access_token --project=unipos-stg > private_repo_access_token.txt' ]
    id: 'get private_repo_access_token'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '.']


substitutions:
  _IMAGE_NAME: logger

images:
  - gcr.io/$PROJECT_ID/${_IMAGE_NAME}